version: 0.2

phases:
  build:
    commands:
      - echo Building and tagging Docker image
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 537486183366.dkr.ecr.eu-central-1.amazonaws.com
      - docker build -t policy-prod .
      - docker tag policy-prod:latest 537486183366.dkr.ecr.eu-central-1.amazonaws.com/policy-prod:latest

  post_build:
    commands:
      - echo Pushing to ECR
      - docker push 537486183366.dkr.ecr.eu-central-1.amazonaws.com/policy-prod:latest
      - printf '[{"name":"policy-prod","imageUri":"537486183366.dkr.ecr.eu-central-1.amazonaws.com/policy-prod:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
